---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    #source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r cars}
data("instacart")
popular_items = 
  instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  select("aisle", "order_number", "product_name") %>% 
  count(aisle, product_name, sort = TRUE) %>% 
  filter(
   n > 200, n < 1000
  ) %>%
  plot_ly(x = ~product_name, y = ~n,  type = "scatter", mode = "markers", colors = "viridis")
popular_items
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
aisle_num = instacart %>% 
  distinct(aisle, .keep_all = TRUE) %>% 
  count()

ordered_num_from_aisles = 
  instacart %>%
  count(aisle,sort = TRUE)

ordered_num_from_aisles %>% 
  mutate(aisle = fct_reorder(aisle,n)) %>% 
  filter(
    n > 12000
  ) %>% 
  plot_ly(x = ~n, y = ~aisle, color = ~aisle, type = "bar", colors = "viridis")

#ordered_num_from_aisles

```

### Chart C

```{r}
instacart %>%  
  filter(
    order_dow == "0"
  ) %>% 
  mutate(neighbourhood = fct_reorder(department, order_number)) %>% 
  plot_ly(x = ~order_number, color = ~department, type = "box", colors = "viridis")
```

